### ISSUE TITLE
ERROR Could not load '/Users/chip.eyler/.config/wtf/config.yml'.

### ISSUE THREAD

**Issue by freqn** [tedmiston/wtf-covid-19-ohio#1]
Getting the following error after building the image with `docker build -t "name:dockerfile" .`:

```
➜  wtf-covid-19-ohio git:(master) wtfutil

ERROR Could not load '/Users/chip.eyler/.config/wtf/config.yml'.

This could mean one of two things:

    1. That file doesn't exist.
    2. That file has a YAML syntax error. Try running it through http://www.yamllint.com to check for errors.

Error: yaml: line 3: mapping values are not allowed in this context
```

`cat /Users/chip.eyler/.config/wtf/config.yml` reveals that I have the file and it's verbatim, from the readme

When using the linter, I get `(<unknown>): mapping values are not allowed in this context at line 3 column 7`

Thoughts?

**Comment by tedmiston** [comment]
I ran my config through YAMLLint and I think it was invalid.

Try changing this line in the config from:

```
args: [ run, --rm, tedmiston/wtf-covid-19-ohio:latest ]
```

to:

```
args: [ "run", "--rm", "tedmiston/wtf-covid-19-ohio:latest" ]
```

**Comment by freqn** [comment]
Thanks for the repsonse! Didn't do the trick :(. Trying a couple of other things.

**Comment by freqn** [comment]
GOT IT! I removed some rogue ... separators I noticed in the file, then it ran like a charm. Nice tool!

**Comment by tedmiston** [comment]
Awesome!  Thank you for checking it out!
